"""Dated count cohorts and their complete predictive trajectories in one value."""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd

from .dates import to_day


def _validate_counts(values, name, *, copy=True):
    """Preserve integer precision, including int64 values beyond float64's exact range."""
    array = np.asarray(values)
    maximum = np.iinfo(np.int64).max
    if array.size == 0:
        return np.empty(array.shape, dtype=np.int64)
    if array.dtype.kind in "iu":
        invalid = (array < 0).any() or (array > maximum).any()
    elif array.dtype.kind == "f":
        invalid = (
            not np.isfinite(array).all()
            or (array < 0).any()
            or (array != np.floor(array)).any()
            or (array >= 2**63).any()
        )
    elif array.dtype.kind == "O":
        result = np.empty(array.shape, dtype=np.int64)
        for index, value in enumerate(array.flat):
            if (
                not isinstance(value, (int, float, np.integer, np.floating))
                or isinstance(value, (bool, np.bool_))
                or not 0 <= value <= maximum
                or value != int(value)
                or int(value) > maximum
            ):
                raise ValueError(f"{name} must be finite nonnegative integer-valued int64 counts")
            result.flat[index] = int(value)
        return result
    else:
        invalid = True
    if invalid:
        raise ValueError(f"{name} must be finite nonnegative integer-valued int64 counts")
    return array.astype(np.int64, copy=copy)


@dataclass(frozen=True)
class SalesForecast:
    """One source scenario: cohort metadata, counts[draw, cohort], and draw labels.

    ``cohorts`` contains ``item_id``, ``sale_date``, and static attributes.
    ``counts`` is authoritative; an input quantity metadata column is removed.
    A single count path broadcasts when composed with multiple parameter draws.
    ``posterior_id`` identifies sources generated by a fitted network so their
    labels can preserve posterior pairing. External scenarios are not conditioning.
    """

    cohorts: pd.DataFrame
    counts: np.ndarray
    draw_ids: np.ndarray | None = None
    posterior_id: str | None = None

    def __post_init__(self):
        if not isinstance(self.cohorts, pd.DataFrame):
            raise TypeError("cohorts must be a pandas DataFrame")
        if not self.cohorts.columns.is_unique:
            raise ValueError("cohort column names must be unique")
        missing = {"item_id", "sale_date"} - set(self.cohorts.columns)
        if missing:
            raise ValueError(f"cohorts missing required columns: {sorted(missing)}")
        cohorts = (
            self.cohorts.drop(columns="quantity", errors="ignore").reset_index(drop=True).copy()
        )
        cohorts["sale_date"] = to_day(cohorts["sale_date"])
        if cohorts["sale_date"].isna().any():
            raise ValueError("cohort sale_date must not be missing")
        if cohorts["item_id"].isna().any() or cohorts["item_id"].duplicated().any():
            raise ValueError("cohort item_id values must be nonmissing and unique")
        if "draw" in cohorts:
            raise ValueError("draw labels belong to draw_ids, not cohort metadata")
        counts = _validate_counts(self.counts, "counts")
        if counts.ndim != 2 or counts.shape[0] == 0 or counts.shape[1] != len(cohorts):
            raise ValueError("counts must have shape [nonempty draw, cohort] aligned to cohorts")
        # Ordinary counts need no Python-integer reduction. Only a potentially
        # overflowing row needs exact accumulation beyond the int64 range.
        maximum = np.iinfo(np.int64).max
        threshold = maximum // max(len(cohorts), 1)
        for row in counts[counts.max(axis=1, initial=0) > threshold]:
            if sum(map(int, row)) > maximum:
                raise ValueError("total sales in a draw exceed int64 count support")
        ids = (
            np.arange(counts.shape[0])
            if self.draw_ids is None
            else np.asarray(self.draw_ids, dtype=object)
        )
        if ids.ndim != 1 or len(ids) != counts.shape[0]:
            raise ValueError("draw_ids must have one label per count draw")
        labels = pd.Series(ids)
        if labels.isna().any() or labels.duplicated().any():
            raise ValueError("draw_ids must be nonmissing and unique")
        if self.posterior_id is not None and not isinstance(self.posterior_id, str):
            raise TypeError("posterior_id must be a string or None")
        ids = ids.copy()
        ids.setflags(write=False)
        counts.setflags(write=False)
        object.__setattr__(self, "cohorts", cohorts)
        object.__setattr__(self, "counts", counts)
        object.__setattr__(self, "draw_ids", ids)

    def __len__(self):
        return len(self.cohorts)

    @classmethod
    def from_frame(cls, frame, *, posterior_id=None):
        """Read sale_date/quantity/static attributes and optional item_id/draw columns.

        Without ``draw``, one row per cohort specifies a fixed scenario. With
        ``draw``, every draw/cohort pair is required exactly once; missing cells
        are not zeros. Cohorts and draw labels retain first-appearance ordering.
        """
        if not isinstance(frame, pd.DataFrame):
            raise TypeError("frame must be a pandas DataFrame")
        if not frame.columns.is_unique or not {"sale_date", "quantity"} <= set(frame.columns):
            raise ValueError("frame requires unique columns including sale_date and quantity")
        work = frame.reset_index(drop=True).copy()
        work["sale_date"] = to_day(work["sale_date"])
        if work.sale_date.isna().any():
            raise ValueError("sale_date must not be missing")
        metadata = [c for c in work.columns if c not in ("quantity", "draw")]
        has_id = "item_id" in work
        if has_id and work.item_id.isna().any():
            raise ValueError("item_id must not be missing")
        keys = ["item_id"] if has_id else metadata
        codes, unique = pd.factorize(pd.MultiIndex.from_frame(work[keys]), sort=False)
        first = np.sort(np.unique(codes, return_index=True)[1])
        cohorts = work.iloc[first][metadata].copy()
        if has_id and len(work[metadata].drop_duplicates()) != len(cohorts):
            raise ValueError("cohort metadata disagrees across draws")
        if not has_id:
            cohorts.insert(0, "item_id", [f"future_{i}" for i in range(len(cohorts))])
        if "draw" in work:
            if work.draw.isna().any() or len(work) == 0:
                raise ValueError(
                    "draw labels must be nonmissing and identify at least one trajectory"
                )
            draw_codes, draw_ids = pd.factorize(work.draw, sort=False)
            pairs = pd.MultiIndex.from_arrays([draw_codes, codes])
            if not pairs.is_unique:
                raise ValueError("duplicate draw/cohort pair")
            if len(work) != len(draw_ids) * len(unique):
                raise ValueError("missing draw/cohort cells are not implicit zeros")
            order = np.argsort(draw_codes * len(unique) + codes)
            counts = work.quantity.to_numpy()[order].reshape(len(draw_ids), len(unique))
        else:
            if len(work) != len(unique):
                raise ValueError("duplicate cohort rows without draw labels")
            counts, draw_ids = work.quantity.to_numpy()[None, :], None
        return cls(cohorts, counts, draw_ids=draw_ids, posterior_id=posterior_id)

    @classmethod
    def from_numpyro_forecast(
        cls, samples, dates, *, groups=None, prefix="future", posterior_id=None
    ):
        """Bind exact upstream [draw, future_day, group] counts to dates and groups.

        The cohort order is date-major: every group on the first day, then every
        group on the next. Multiple series require an explicit group metadata table.
        """
        draws = np.asarray(samples)
        if draws.ndim != 3 or any(size == 0 for size in draws.shape):
            raise ValueError("samples must have nonempty shape [draw, future_day, group]")
        d, horizon, g = draws.shape
        days = np.asarray(to_day(dates))
        if days.ndim != 1 or len(days) != horizon or np.isnat(days).any():
            raise ValueError("dates must match the forecast time axis and contain no missing days")
        if not np.all(np.diff(days) == np.timedelta64(1, "D")):
            raise ValueError("forecast dates must be consecutive, unique and increasing")
        if groups is None:
            if g != 1:
                raise ValueError("groups metadata is required for multiple sales series")
            groups = pd.DataFrame(index=range(1))
        if not isinstance(groups, pd.DataFrame) or len(groups) != g:
            raise ValueError("groups must be a DataFrame aligned to the observation axis")
        if not groups.columns.is_unique or set(groups.columns) & {
            "item_id",
            "sale_date",
            "quantity",
            "draw",
        }:
            raise ValueError(
                "group attributes cannot overwrite identifiers, dates, counts or draw labels"
            )
        metadata = {
            "item_id": [f"{prefix}_{i}" for i in range(horizon * g)],
            "sale_date": np.repeat(days, g),
        }
        metadata.update({col: np.tile(groups[col].to_numpy(), horizon) for col in groups})
        return cls(pd.DataFrame(metadata), draws.reshape(d, horizon * g), posterior_id=posterior_id)

    def to_frame(self):
        """Return a complete long draw/cohort/quantity table without averaging."""
        d, c = self.counts.shape
        frame = self.cohorts.iloc[np.tile(np.arange(c), d)].reset_index(drop=True)
        frame.insert(0, "draw", np.repeat(self.draw_ids, c))
        frame["quantity"] = self.counts.reshape(-1)
        return frame
