"""Throwaway experiment: exact calendar-axis cure process as a NumPyro Forecast ``markov_series``.

Question: can the per-unit mixture-cure event process (delayed entry, per-unit
covariates, hard closures, at most one event per unit, future births) be written
as a stateful date-axis ``markov_series`` whose observed prefix is conditioned and
whose forecast suffix is generated by the native ``forecast`` driver, without
aggregating units or inferring discrete latents?

Formulation. With ``q[t, u] = P(event on day t | event-free before t)`` the
cure-marginalized effective hazard from ``CalendarCase.arrays`` (zero before entry,
on closed days, before birth and past the deadline), the unit path is a Bernoulli
chain with a boolean at-risk carry: ``event[t, u] ~ Bernoulli(q[t, u])`` while at
risk, a certain zero otherwise, and ``pending <- pending & ~event``. Its likelihood
``prod_{s<e} (1 - q_s) q_e`` (or ``prod_{s<stop} (1 - q_s)`` when censored) is the
exact conditional-entry mixture-cure likelihood, because ``q`` is the hazard of the
marginal process. The step distributions carry the process support themselves: a
supplied event on an off-risk day (closed, pre-entry, unborn, past deadline, after
an earlier event), a non-binary value, a negative count or a count beyond the
remaining cohort scores ``-inf`` rather than 0 (a mask) or a clamp floor.
Cohort counts of units with identical hazard profiles follow the same recursion
with ``Binomial(remaining, q)`` transitions; the count likelihood equals the summed
unit likelihood plus ``sum_t log C(remaining_t, events_t)``, which is free of theta.

Run with: uv run --extra forecast python examples/prototype_native_markov.py
"""

import json
import sys
from dataclasses import replace
from math import comb

import jax
import jax.numpy as jnp
import numpy as np
import numpyro
import numpyro.distributions as dist
from jax import lax, random
from jax.scipy.special import gammaln, xlog1py, xlogy
from numpyro import handlers
from numpyro.distributions import constraints
from numpyro.distributions.util import binomial, promote_shapes
from numpyro.infer import SVI, Trace_ELBO
from numpyro.infer.autoguide import AutoNormal
from numpyro.infer.util import log_density
from numpyro_forecast import Horizon, draw_posterior, forecast, markov_series
from prototype_native_common import TRUTH, check_paths, fit_and_forecast, make_case, sample_theta


class AtRiskBernoulli(dist.Distribution):
    """Bernoulli(probs) while at risk, a certain zero otherwise, ``-inf`` outside that support."""

    arg_constraints = {"probs": constraints.unit_interval, "at_risk": constraints.boolean}
    support = constraints.boolean

    def __init__(self, probs, at_risk, *, validate_args=None):
        self.probs, self.at_risk = promote_shapes(probs, at_risk)
        batch_shape = lax.broadcast_shapes(jnp.shape(probs), jnp.shape(at_risk))
        super().__init__(batch_shape=batch_shape, validate_args=validate_args)

    def sample(self, key, sample_shape=()):
        draw = random.bernoulli(
            key, jnp.where(self.at_risk, self.probs, 0.0), shape=sample_shape + self.batch_shape
        )
        return draw.astype(jnp.result_type(draw, int))

    def log_prob(self, value):
        binary = (value == 0) | (value == 1)
        v = jnp.where(binary, value, 0).astype(jnp.result_type(float))
        on_risk = xlogy(v, self.probs) + xlog1py(1.0 - v, -self.probs)
        off_risk = jnp.where(v == 0, 0.0, -jnp.inf)
        return jnp.where(binary, jnp.where(self.at_risk, on_risk, off_risk), -jnp.inf)


class DepletingBinomial(dist.Distribution):
    """Binomial(remaining, probs) while the cohort is at risk, a certain zero otherwise, ``-inf`` outside."""

    arg_constraints = {
        "probs": constraints.unit_interval,
        "total_count": constraints.nonnegative_integer,
        "at_risk": constraints.boolean,
    }
    support = constraints.nonnegative_integer

    def __init__(self, probs, total_count, at_risk, *, validate_args=None):
        self.probs, self.total_count, self.at_risk = promote_shapes(probs, total_count, at_risk)
        batch_shape = lax.broadcast_shapes(
            jnp.shape(probs), jnp.shape(total_count), jnp.shape(at_risk)
        )
        super().__init__(batch_shape=batch_shape, validate_args=validate_args)

    def sample(self, key, sample_shape=()):
        return binomial(
            key,
            jnp.where(self.at_risk, self.probs, 0.0),
            n=self.total_count,
            shape=sample_shape + self.batch_shape,
        )

    def log_prob(self, value):
        n = self.total_count
        inside = (value >= 0) & (value <= n) & (value == jnp.round(value))
        k = jnp.where(inside, value, 0).astype(jnp.result_type(float))
        on_risk = (
            gammaln(n + 1.0)
            - gammaln(k + 1.0)
            - gammaln(n - k + 1.0)
            + xlogy(k, self.probs)
            + xlog1py(n - k, -self.probs)
        )
        off_risk = jnp.where(k == 0, 0.0, -jnp.inf)
        return jnp.where(inside, jnp.where(self.at_risk, on_risk, off_risk), -jnp.inf)


def unit_transition(pending, x_t):
    """One calendar day for every unit: at-risk units draw an event, others stay at zero with certainty."""
    q_t, open_t = x_t
    return AtRiskBernoulli(q_t, open_t & pending), lambda event: pending & (event == 0)


def stock_unit_transition(masked):
    """The same step with NumPyro's Bernoulli, with or without ``.mask``, for the support probe."""

    def transition(pending, x_t):
        q_t, open_t = x_t
        at_risk = open_t & pending
        step = dist.Bernoulli(probs=jnp.where(at_risk, q_t, 0.0))
        return (step.mask(at_risk) if masked else step), lambda event: pending & (event == 0)

    return transition


def require_integer(data):
    """Event and count data are integer-valued by dtype, the same contract ``predict()`` enforces for counts."""
    if data is not None and not jnp.issubdtype(data.dtype, jnp.integer):
        msg = f"event data must be integer-dtyped, got {data.dtype}"
        raise ValueError(msg)


def make_unit_model(case, transition=unit_transition):
    def model(covariates, data=None):
        require_integer(data)
        h = Horizon.from_data(covariates, data)
        theta = sample_theta()
        q, open_days = case.arrays(theta, h.duration)
        with handlers.condition(data={"event": h.data}):
            event = markov_series(
                h, "event", jnp.ones(len(case.origin), dtype=bool), transition, xs=(q, open_days)
            )
        if h.future > 0:
            numpyro.deterministic("forecast", event[h.t_obs :])

    return model


def cohort_profiles(case, features=None):
    """Group units whose hazard inputs are identical on every day (origin, entry, static, dynamic, closures)."""
    features = case.features if features is None else features
    groups, index = [], {}
    for u in range(len(case.origin)):
        key = (
            int(case.origin[u]),
            int(case.entry[u]),
            case.cure_features[u].tobytes(),
            np.ascontiguousarray(features[u]).tobytes(),
            np.ascontiguousarray(case.allowed[u]).tobytes(),
        )
        if key not in index:
            index[key] = len(groups)
            groups.append([])
        groups[index[key]].append(u)
    return groups


def cohort_transition(remaining, x_t):
    """One calendar day per cohort: remaining at-risk units deplete through a Binomial draw."""
    q_t, open_t = x_t
    return DepletingBinomial(
        q_t, remaining, open_t & (remaining > 0)
    ), lambda events: remaining - events


def stock_cohort_transition(remaining, x_t):
    """The same step with NumPyro's masked Binomial, for the support probe."""
    q_t, open_t = x_t
    at_risk = open_t & (remaining > 0)
    step = dist.Binomial(total_count=remaining, probs=jnp.where(at_risk, q_t, 0.0)).mask(at_risk)
    return step, lambda events: remaining - events


def make_cohort_model(case, groups, transition=cohort_transition):
    representative = np.array([g[0] for g in groups])
    sizes = jnp.asarray([len(g) for g in groups], dtype=jnp.int32)

    def model(covariates, data=None):
        require_integer(data)
        h = Horizon.from_data(covariates, data)
        theta = sample_theta()
        q, open_days = case.arrays(theta, h.duration)
        with handlers.condition(data={"count": h.data}):
            events = markov_series(
                h,
                "count",
                sizes,
                transition,
                xs=(q[:, representative], open_days[:, representative]),
            )
        if h.future > 0:
            numpyro.deterministic("forecast", events[h.t_obs :])

    return model


def membership(case, groups):
    m = np.zeros((len(case.origin), len(groups)), dtype=np.int32)
    for c, units in enumerate(groups):
        m[units, c] = 1
    return m


def observed_log_likelihood(model, theta, x, y):
    """Model log density of the observed prefix with the theta prior removed."""
    joint, _ = log_density(handlers.substitute(model, {"theta": theta}), (x, y), {}, {})
    return joint - dist.Normal(0.0, 1.0).log_prob(theta).sum()


def thetas_for_parity(count=4):
    thetas = [jnp.asarray(TRUTH, dtype=jnp.float32)]
    for seed in range(count):
        with handlers.seed(rng_seed=seed):
            thetas.append(sample_theta())
    return thetas


def parity(case, model, x, y, thetas, extra=0.0):
    """Compare model prefix log-likelihood and gradient against the TTENet reference."""
    ll = jax.jit(lambda th: observed_log_likelihood(model, th, x, y))
    ref = jax.jit(lambda th: case.reference(th).sum())
    grad_ll, grad_ref = jax.jit(jax.grad(ll)), jax.jit(jax.grad(ref))
    rows = []
    for theta in thetas:
        a, b = float(ll(theta)), float(ref(theta)) + float(extra)
        ga, gb = np.asarray(grad_ll(theta)), np.asarray(grad_ref(theta))
        rows.append(
            {
                "theta": np.round(np.asarray(theta), 4).tolist(),
                "ll_model": a,
                "ll_reference": b,
                "ll_abs_diff": abs(a - b),
                "ll_rel_diff": abs(a - b) / abs(b),
                "grad_max_abs_diff": float(np.max(np.abs(ga - gb))),
                "grad_max_rel_diff": float(np.max(np.abs(ga - gb) / np.maximum(np.abs(gb), 1e-6))),
                "grad_finite": bool(np.isfinite(ga).all()),
            }
        )
    return rows


def corrupted_unit_prefixes(case, theta):
    """Prefixes that leave the unit process support, each cell derived from the fixture."""
    stop = case.t_obs
    base = case.data[:stop]
    _, open_days = (np.asarray(a) for a in case.arrays(theta, stop))
    day = np.arange(stop)[:, None]
    pending_before = (np.cumsum(base, axis=0) - base) == 0
    born, entered = day >= case.origin[None, :], day >= case.entry[None, :]
    within = day - case.origin[None, :] <= case.deadline
    allowed = case.allowed[:, :stop].T
    cells = {
        "closed_day": (~allowed & born & entered & within & pending_before, 1),
        "repeat_event": (open_days & ~pending_before, 1),
        "before_entry": (allowed & born & ~entered, 1),
        "before_birth": (allowed & ~born, 1),
        "past_deadline": (allowed & born & ~within & pending_before, 1),
        "non_binary": (open_days & pending_before, 2),
    }
    out = {}
    for name, (mask, value) in cells.items():
        t, u = np.argwhere(mask)[0]
        data = base.copy()
        data[t, u] = value
        out[name] = (data, (int(t), int(u)), value)
    return out


def corrupted_count_prefixes(case, groups, m, theta):
    """Prefixes that leave the cohort count support."""
    stop = case.t_obs
    counts = (np.asarray(case.data) @ m)[:stop]
    sizes = m.sum(axis=0)
    _, open_days = (np.asarray(a) for a in case.arrays(theta, stop))
    open_cohort = open_days[:, [g[0] for g in groups]]
    remaining = sizes[None, :] - (np.cumsum(counts, axis=0) - counts)
    at_risk = open_cohort & (remaining > 0)
    t0, u0 = np.argwhere(at_risk)[0]
    tc, uc = np.argwhere(~open_cohort & (remaining > 0))[0]
    td, ud = np.argwhere(open_cohort & (remaining == 0))[0]
    cells = {
        "negative": (t0, u0, -1),
        "exceeds_remaining": (t0, u0, int(remaining[t0, u0]) + 1),
        "closed_day": (tc, uc, 1),
        "depleted_cohort": (td, ud, 1),
        "fractional": (t0, u0, 0.5),
    }
    out = {}
    for name, (t, u, value) in cells.items():
        data = counts.astype(np.float32 if name == "fractional" else np.int32)
        data[t, u] = value
        out[name] = (data, (int(t), int(u)), value)
    return out


def support_probe(case, x, theta, groups, m):
    """Supplied prefixes outside the process support must score -inf; stock families score a mask 0 or a clamp."""
    xp = x[: case.t_obs]
    unit_models = {
        "exact": make_unit_model(case),
        "stock_masked": make_unit_model(case, stock_unit_transition(True)),
        "stock_unmasked": make_unit_model(case, stock_unit_transition(False)),
    }
    count_models = {
        "exact": make_cohort_model(case, groups),
        "stock_masked": make_cohort_model(case, groups, stock_cohort_transition),
    }

    scorers = {
        kind: {
            name: jax.jit(lambda th, y, model=model: observed_log_likelihood(model, th, xp, y))
            for name, model in models.items()
        }
        for kind, models in (("unit", unit_models), ("cohort", count_models))
    }

    def score(kind, data):
        out = {}
        for name, fn in scorers[kind].items():
            try:
                out[name] = float(fn(theta, jnp.asarray(data)))
            except ValueError as err:  # the dtype contract raised at trace time is the measurement
                out[name] = f"{type(err).__name__}: {err}"
        return out

    unit = {
        "valid": {
            **score("unit", case.data[: case.t_obs]),
            "reference": float(case.reference(theta).sum()),
        }
    }
    for name, (data, cell, value) in corrupted_unit_prefixes(case, theta).items():
        unit[name] = {"cell": cell, "value": value, **score("unit", data)}
    cohort = {"valid": score("cohort", (np.asarray(case.data) @ m)[: case.t_obs])}
    for name, (data, cell, value) in corrupted_count_prefixes(case, groups, m, theta).items():
        cohort[name] = {"cell": cell, "value": value, **score("cohort", data)}
    return {
        "unit": unit,
        "cohort": cohort,
        "stock_clamp_floor_log": float(np.log(np.finfo(np.float32).tiny)),
    }


def substitute_probe(case, x, y):
    """Record what happens when the prefix is substituted rather than conditioned."""

    def model(covariates, data=None):
        h = Horizon.from_data(covariates, data)
        theta = sample_theta()
        q, open_days = case.arrays(theta, h.duration)
        with handlers.substitute(data={"event": h.data}):
            markov_series(
                h,
                "event",
                jnp.ones(len(case.origin), dtype=bool),
                unit_transition,
                xs=(q, open_days),
            )

    trace = handlers.trace(handlers.seed(model, 0)).get_trace(x, y)
    site = trace["event"]
    note = {
        "value_equals_data": bool(np.array_equal(np.asarray(site["value"]), np.asarray(y))),
        "is_observed": bool(site["is_observed"]),
    }
    try:
        SVI(model, AutoNormal(model), numpyro.optim.Adam(0.025), Trace_ELBO()).init(
            random.PRNGKey(0), x, y
        )
        note["autonormal_svi_init"] = "accepted"
    except Exception as err:  # noqa: BLE001 - the message is the measurement
        note["autonormal_svi_init"] = f"{type(err).__name__}: {err}"
    return note


def law_check(empirical, analytic, variance=None):
    """Z-scores of Monte Carlo cell means against an analytic law; structural zeros must be exact.

    ``variance`` is the per-cell variance of one draw; it defaults to the Bernoulli
    ``p(1-p)`` and must be supplied for counts (sum of the member units' ``p(1-p)``).
    """
    draws = empirical.shape[0]
    mean = empirical.mean(axis=0)
    variance = analytic * (1 - analytic) if variance is None else variance
    structural = analytic == 0
    se = np.sqrt(np.maximum(variance, 1e-12) / draws)
    z = np.where(structural, 0.0, (mean - analytic) / se)
    return {
        "draws": int(draws),
        "cells": int(analytic.size),
        "structural_zero_cells": int(structural.sum()),
        "structural_zero_violations": int(np.sum(mean[structural] != 0)),
        "max_abs_z": float(np.max(np.abs(z))),
        "cells_beyond_3se": int(np.sum(np.abs(z) > 3)),
        "max_abs_diff": float(np.max(np.abs(mean - analytic))),
        "total_prob_analytic": float(analytic.sum()),
        "total_prob_empirical": float(mean.sum()),
    }


def truth_draws(model, x, y, draws, seed):
    theta = jnp.broadcast_to(jnp.asarray(TRUTH, dtype=jnp.float32), (draws, len(TRUTH)))
    return np.asarray(forecast(random.PRNGKey(seed), model, {"theta": theta}, y, x))


def unit_future_law(case, model, x, y, draws):
    paths = truth_draws(model, x, y, draws, 7)
    summary = check_paths(case, paths)
    summary.update(law_check(paths, case.analytic_future(TRUTH)))
    totals = paths.sum(axis=1)  # [draws, units], each 0/1
    live = totals.std(axis=0) > 0
    corr = np.corrcoef(totals[:, live].T)
    np.fill_diagonal(corr, 0.0)
    summary["max_abs_cross_unit_corr"] = float(np.max(np.abs(corr)))
    summary["independence_3se"] = float(3 / np.sqrt(draws))
    return summary


def carry_probe(case, model, x, draws):
    """Prefix events must switch units off in the forecast; future births must switch on at their origin."""
    altered = case.data[: case.t_obs].copy()
    _, open_true = (np.asarray(a) for a in case.arrays(jnp.asarray(TRUTH), case.t_obs))
    pending = ~altered.any(axis=0)
    candidates = [u for u in range(len(case.origin)) if pending[u] and open_true[:, u].any()]
    day = int(np.flatnonzero(open_true[:, candidates[0]])[-1])
    altered[day, candidates[0]] = 1
    paths = truth_draws(model, x, jnp.asarray(altered), draws, 11)
    analytic = case.analytic_future(TRUTH).copy()
    analytic[:, candidates[0]] = 0.0
    future_born = np.flatnonzero(case.origin >= case.t_obs)
    first_event_day = {}
    for u in future_born:
        days = np.flatnonzero(paths[:, :, u].any(axis=0))
        first_event_day[int(u)] = None if days.size == 0 else int(days[0] + case.t_obs)
    return {
        "unit_switched_off": int(candidates[0]),
        "added_event_day": day,
        "events_after_added_prefix_event": int(paths[:, :, candidates[0]].sum()),
        "law_after_alteration": law_check(paths, analytic),
        "future_born_units": future_born.tolist(),
        "future_born_origin": case.origin[future_born].tolist(),
        "future_born_first_event_day": first_event_day,
        "future_born_event_rate": {
            int(u): float(paths[:, :, u].sum(axis=1).mean()) for u in future_born
        },
        "future_born_analytic_rate": {int(u): float(analytic[:, u].sum()) for u in future_born},
    }


def cohort_experiment(case, unit_model, x, thetas, steps, draws, law_draws, short_stop=8):
    groups = cohort_profiles(case)
    m = membership(case, groups)
    counts = np.asarray(case.data) @ m  # [day, cohort]
    sizes = m.sum(axis=0)
    model = make_cohort_model(case, groups)

    def count_prefix(stop):
        prefix = counts[:stop]
        remaining = sizes[None, :] - np.concatenate(
            [np.zeros((1, len(groups)), dtype=int), np.cumsum(prefix, axis=0)[:-1]]
        )
        combinatorial = float(
            np.sum(gammaln(remaining + 1) - gammaln(prefix + 1) - gammaln(remaining - prefix + 1))
        )
        return jnp.asarray(prefix, dtype=jnp.int32), combinatorial

    def count_checks(paths, stop):
        _, eligible = case.arrays(jnp.asarray(TRUTH))
        open_cohort = np.asarray(eligible)[stop:][:, [g[0] for g in groups]]
        cumulative = np.cumsum(paths, axis=1) + counts[:stop].sum(axis=0)[None, None, :]
        return {
            "shape": list(paths.shape),
            "negative": int((paths < 0).sum()),
            "exceeds_cohort_size": int((cumulative > sizes[None, None, :]).sum()),
            "closed_day_events": int(paths[:, ~open_cohort].sum()),
        }

    y_counts, combinatorial = count_prefix(case.t_obs)
    rows = parity(case, model, x[: case.t_obs], y_counts, thetas, extra=combinatorial)

    # Native fit + forecast on cohort counts (mirrors common.fit_and_forecast with count checks).
    guide = AutoNormal(model)
    svi = SVI(model, guide, numpyro.optim.Adam(0.025), Trace_ELBO())
    fitted = svi.run(random.PRNGKey(201), steps, x[: case.t_obs], y_counts, progress_bar=False)
    posterior = draw_posterior(random.PRNGKey(202), guide, fitted.params, draws)
    fitted_paths = np.asarray(forecast(random.PRNGKey(203), model, posterior, y_counts, x))

    # Sampler-versus-sampler comparison at an early split where the multi-unit cohorts are still at risk.
    short = replace(case, t_obs=short_stop)
    y_short, _ = count_prefix(short_stop)
    unit_paths = truth_draws(unit_model, x, jnp.asarray(short.data[:short_stop]), law_draws, 13)
    unit_summary = check_paths(short, unit_paths)
    count_paths = truth_draws(model, x, y_short, law_draws, 17)
    aggregated = unit_paths @ m  # unit-model draws summed within cohort
    analytic_unit = short.analytic_future(TRUTH)
    diff = count_paths.mean(axis=0) - aggregated.mean(axis=0)
    se = np.sqrt((count_paths.var(axis=0) + aggregated.var(axis=0)) / law_draws)
    z = np.where(se > 0, diff / np.where(se > 0, se, 1.0), 0.0)
    totals = {}
    for c in np.flatnonzero(sizes > 1):
        # Units in a cohort share p, so the future total is Binomial(remaining, p) exactly.
        p = float(analytic_unit[:, groups[c][0]].sum())
        remaining = int(sizes[c] - counts[:short_stop, c].sum())
        exact = np.array(
            [
                comb(remaining, i) * p**i * (1 - p) ** (remaining - i) if i <= remaining else 0.0
                for i in range(sizes[c] + 1)
            ]
        )
        pmfs = {
            name: np.bincount(paths[:, :, c].sum(axis=1), minlength=sizes[c] + 1) / law_draws
            for name, paths in (("count_model", count_paths), ("unit_model", aggregated))
        }
        se_pmf = np.sqrt(np.maximum(exact * (1 - exact), 1e-12) / law_draws)
        totals[str(int(c))] = {
            "units": groups[c],
            "remaining_at_split": remaining,
            "unit_future_event_prob": p,
            "exact_pmf": exact.round(4).tolist(),
            **{f"{name}_pmf": pmf.round(4).tolist() for name, pmf in pmfs.items()},
            **{
                f"{name}_max_abs_z": float(np.max(np.abs((pmf - exact) / se_pmf)[exact > 0]))
                for name, pmf in pmfs.items()
            },
            "structural_zero_violations": int(
                sum(np.sum(pmf[exact == 0] != 0) for pmf in pmfs.values())
            ),
        }

    heterogeneous = case.features.copy()
    heterogeneous[:, :, 0] += np.random.default_rng(3).normal(size=(len(case.origin), 1)) * 0.01
    return (
        {
            "groups": groups,
            "cohorts": len(groups),
            "units": len(case.origin),
            "singleton_cohorts": int(np.sum(sizes == 1)),
            "profile_key": [
                "origin",
                "entry",
                "cure_features",
                "features[day, feature] row",
                "allowed[day] row",
            ],
            "cohorts_with_unit_continuous_covariate": len(cohort_profiles(case, heterogeneous)),
            "combinatorial_factor": combinatorial,
            "parity_vs_unit_reference_plus_combinatorial": rows,
            "fit_forecast": {
                **count_checks(fitted_paths, case.t_obs),
                "elbo_final": float(fitted.losses[-1]),
                "elbo_finite": bool(np.isfinite(fitted.losses).all()),
                "posterior_sites": sorted(posterior),
            },
            "split_for_sampler_comparison": short_stop,
            "unit_paths_at_split": unit_summary,
            "count_checks_at_split": count_checks(count_paths, short_stop),
            "count_law_vs_analytic_unit_sums": law_check(
                count_paths, analytic_unit @ m, variance=(analytic_unit * (1 - analytic_unit)) @ m
            ),
            "count_vs_aggregated_unit_draws": {
                "max_abs_z": float(np.max(np.abs(z))),
                "cells_beyond_3se": int(np.sum(np.abs(z) > 3)),
                "max_abs_mean_diff": float(np.max(np.abs(diff))),
            },
            "multi_unit_cohort_totals": totals,
        },
        groups,
        m,
    )


def run(steps=100, draws=128, law_draws=16000):
    case = make_case()
    x, y = case.covariates, jnp.asarray(case.data[: case.t_obs])
    model = make_unit_model(case)
    thetas = thetas_for_parity()
    unit_parity = parity(case, model, x[: case.t_obs], y, thetas)
    smoke = fit_and_forecast(model, case, steps=steps, draws=draws)
    law = unit_future_law(case, model, x, y, law_draws)
    carry = carry_probe(case, model, x, law_draws)
    cohort, groups, m = cohort_experiment(case, model, x, thetas, steps, draws, law_draws)
    return {
        "unit_model": {
            "parity_vs_reference": unit_parity,
            "fit_forecast": smoke,
            "future_law": law,
            "carry": carry,
            "substitute_instead_of_condition": substitute_probe(case, x[: case.t_obs], y),
        },
        "cohort_model": cohort,
        "support": support_probe(case, x, thetas[0], groups, m),
        "api_notes": [
            "markov_series owns the sample statement, so the observed prefix is conditioned with "
            "handlers.condition(data={site: h.data}) around the call; numpyro scan forwards the handler into "
            "the body through its substitute_stack and marks the site is_observed, and a None value is a no-op.",
            "predict() is unused: it registers obs/obs_future for a noise family attached to a deterministic "
            "predictor via slice_time/prefix_condition. Here the observation is the Markov chain itself and "
            "its prefix conditional lives in the carry, so the model registers the forecast deterministic from "
            "the future scan suffix, which is the same site forecast() reads.",
            "The step distributions AtRiskBernoulli / DepletingBinomial own the process support: off-risk cells "
            "are a certain zero with log_prob(1) = -inf, and non-binary, negative, fractional or over-remaining "
            "values score -inf. NumPyro's Bernoulli/Binomial clamp probabilities at float32 tiny (log = -87.3) "
            "and .mask(at_risk) scores an impossible supplied event 0; both are measured under support.",
        ],
    }


if __name__ == "__main__":
    print(json.dumps(run(), indent=1, default=float))
    sys.stdout.flush()
